apiVersion: v2
name: aimlinfra-kuberay-operator  # Name of the chart (without team prefix)
description: A Helm chart for KubeRay Operator
version: 0.1.8  # SemVer: MAJOR.MINOR.PATCH
appVersion: "1.0.0"  # Version of the app this chart deploys
home: https://github.com/sadhal/ocp-infra-kaas-customers-helm
sources:
  - https://github.com/sadhal/ocp-infra-kaas-customers-helm
maintainers:
  - name: aimlinfra
    email: aimlinfra@sadmir.se
